export const competitions = [
  {
    id: 2013,
    area: {
      id: 2032,
      name: 'Brazil',
      code: 'BRA',
      flag: 'https://crests.football-data.org/764.svg',
    },
    name: 'Brasileirão',
    code: 'BSA',
    type: 'LEAGUE',
    emblem:
      'https://a4.espncdn.com/combiner/i?img=%2Fi%2Fleaguelogos%2Fsoccer%2F500%2F85.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 2257,
      startDate: '2024-04-13',
      endDate: '2024-12-08',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 8,
    lastUpdated: '2021-07-20T18:42:17Z',
  },
  // {
  //   id: 2016,
  //   area: {
  //     id: 2072,
  //     name: 'England',
  //     code: 'ENG',
  //     flag: 'https://crests.football-data.org/770.svg',
  //   },
  //   name: 'Liga Inglesa (EFL)',
  //   code: 'ELC',
  //   type: 'LEAGUE',
  //   emblem: 'https://crests.football-data.org/ELC.png',
  //   plan: 'TIER_ONE',
  //   currentSeason: {
  //     id: 1573,
  //     startDate: '2023-08-04',
  //     endDate: '2024-05-04',
  //     currentMatchday: 43,
  //     winner: null,
  //   },
  //   numberOfAvailableSeasons: 7,
  //   lastUpdated: '2022-03-20T09:31:30Z',
  // },
  // {
  //   id: 2021,
  //   area: {
  //     id: 2072,
  //     name: 'England',
  //     code: 'ENG',
  //     flag: 'https://crests.football-data.org/770.svg',
  //   },
  //   name: 'Premier League',
  //   code: 'PL',
  //   type: 'LEAGUE',
  //   emblem: 'https://crests.football-data.org/PL.png',
  //   plan: 'TIER_ONE',
  //   currentSeason: {
  //     id: 1564,
  //     startDate: '2023-08-11',
  //     endDate: '2024-05-19',
  //     currentMatchday: 33,
  //     winner: null,
  //   },
  //   numberOfAvailableSeasons: 125,
  //   lastUpdated: '2022-03-20T08:58:54Z',
  // },
  // {
  //   id: 2001,
  //   area: {
  //     id: 2077,
  //     name: 'Europe',
  //     code: 'EUR',
  //     flag: 'https://crests.football-data.org/EUR.svg',
  //   },
  //   name: 'Champions League',
  //   code: 'CL',
  //   type: 'CUP',
  //   emblem: 'https://crests.football-data.org/CL.png',
  //   plan: 'TIER_ONE',
  //   currentSeason: {
  //     id: 1630,
  //     startDate: '2023-09-19',
  //     endDate: '2024-06-01',
  //     currentMatchday: 6,
  //     winner: null,
  //   },
  //   numberOfAvailableSeasons: 44,
  //   lastUpdated: '2022-03-20T09:20:44Z',
  // },
  // {
  //   id: 2018,
  //   area: {
  //     id: 2077,
  //     name: 'Europe',
  //     code: 'EUR',
  //     flag: 'https://crests.football-data.org/EUR.svg',
  //   },
  //   name: 'Euro Copa',
  //   code: 'EC',
  //   type: 'CUP',
  //   emblem: 'https://crests.football-data.org/EUR.svg',
  //   plan: 'TIER_ONE',
  //   currentSeason: {
  //     id: 1537,
  //     startDate: '2024-06-14',
  //     endDate: '2024-07-14',
  //     currentMatchday: 1,
  //     winner: null,
  //   },
  //   numberOfAvailableSeasons: 17,
  //   lastUpdated: '2021-07-20T18:34:04Z',
  // },
  // {
  //   id: 2015,
  //   area: {
  //     id: 2081,
  //     name: 'France',
  //     code: 'FRA',
  //     flag: 'https://crests.football-data.org/773.svg',
  //   },
  //   name: 'Ligue 1',
  //   code: 'FL1',
  //   type: 'LEAGUE',
  //   emblem: 'https://crests.football-data.org/FL1.png',
  //   plan: 'TIER_ONE',
  //   currentSeason: {
  //     id: 1595,
  //     startDate: '2023-08-13',
  //     endDate: '2024-05-18',
  //     currentMatchday: 29,
  //     winner: null,
  //   },
  //   numberOfAvailableSeasons: 80,
  //   lastUpdated: '2022-03-20T09:30:02Z',
  // },
  // {
  //   id: 2002,
  //   area: {
  //     id: 2088,
  //     name: 'Germany',
  //     code: 'DEU',
  //     flag: 'https://crests.football-data.org/759.svg',
  //   },
  //   name: 'Bundesliga',
  //   code: 'BL1',
  //   type: 'LEAGUE',
  //   emblem: 'https://crests.football-data.org/BL1.png',
  //   plan: 'TIER_ONE',
  //   currentSeason: {
  //     id: 1592,
  //     startDate: '2023-08-18',
  //     endDate: '2024-05-18',
  //     currentMatchday: 29,
  //     winner: null,
  //   },
  //   numberOfAvailableSeasons: 61,
  //   lastUpdated: '2022-03-20T08:52:53Z',
  // },
  // {
  //   id: 2019,
  //   area: {
  //     id: 2114,
  //     name: 'Italy',
  //     code: 'ITA',
  //     flag: 'https://crests.football-data.org/784.svg',
  //   },
  //   name: 'Serie A',
  //   code: 'SA',
  //   type: 'LEAGUE',
  //   emblem: 'https://crests.football-data.org/SA.png',
  //   plan: 'TIER_ONE',
  //   currentSeason: {
  //     id: 1600,
  //     startDate: '2023-08-19',
  //     endDate: '2024-05-26',
  //     currentMatchday: 32,
  //     winner: null,
  //   },
  //   numberOfAvailableSeasons: 92,
  //   lastUpdated: '2022-03-20T09:16:43Z',
  // },
  // {
  //   id: 2003,
  //   area: {
  //     id: 2163,
  //     name: 'Netherlands',
  //     code: 'NLD',
  //     flag: 'https://crests.football-data.org/8601.svg',
  //   },
  //   name: 'Eredivisie',
  //   code: 'DED',
  //   type: 'LEAGUE',
  //   emblem: 'https://crests.football-data.org/ED.png',
  //   plan: 'TIER_ONE',
  //   currentSeason: {
  //     id: 1590,
  //     startDate: '2023-08-11',
  //     endDate: '2024-05-19',
  //     currentMatchday: 30,
  //     winner: null,
  //   },
  //   numberOfAvailableSeasons: 68,
  //   lastUpdated: '2022-03-20T09:19:27Z',
  // },
  // {
  //   id: 2017,
  //   area: {
  //     id: 2187,
  //     name: 'Portugal',
  //     code: 'POR',
  //     flag: 'https://crests.football-data.org/765.svg',
  //   },
  //   name: 'Primeira Liga PT',
  //   code: 'PPL',
  //   type: 'LEAGUE',
  //   emblem: 'https://crests.football-data.org/PPL.png',
  //   plan: 'TIER_ONE',
  //   currentSeason: {
  //     id: 1603,
  //     startDate: '2023-08-13',
  //     endDate: '2024-05-19',
  //     currentMatchday: 29,
  //     winner: null,
  //   },
  //   numberOfAvailableSeasons: 75,
  //   lastUpdated: '2022-03-20T09:34:09Z',
  // },
  {
    id: 2152,
    area: {
      id: 2220,
      name: 'South America',
      code: 'SAM',
      flag: 'https://crests.football-data.org/CLI.svg',
    },
    name: 'Libertadores',
    code: 'CLI',
    type: 'CUP',
    emblem: 'https://crests.football-data.org/CLI.svg',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 1644,
      startDate: '2024-02-07',
      endDate: '2024-05-31',
      currentMatchday: 2,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2023-03-16T16:22:43Z',
  },
  // {
  //   id: 2014,
  //   area: {
  //     id: 2224,
  //     name: 'Spain',
  //     code: 'ESP',
  //     flag: 'https://crests.football-data.org/760.svg',
  //   },
  //   name: 'La Liga',
  //   code: 'PD',
  //   type: 'LEAGUE',
  //   emblem: 'https://crests.football-data.org/PD.png',
  //   plan: 'TIER_ONE',
  //   currentSeason: {
  //     id: 1577,
  //     startDate: '2023-08-13',
  //     endDate: '2024-05-26',
  //     currentMatchday: 31,
  //     winner: null,
  //   },
  //   numberOfAvailableSeasons: 93,
  //   lastUpdated: '2022-03-20T09:20:08Z',
  // },
  {
    id: 2000,
    area: {
      id: 2267,
      name: 'World',
      code: 'INT',
      flag: null,
    },
    name: 'Copa 2022',
    code: 'WC',
    type: 'CUP',
    emblem: 'https://crests.football-data.org/qatar.png',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 1382,
      startDate: '2022-11-20',
      endDate: '2022-12-18',
      currentMatchday: 8,
      winner: {
        id: 762,
        name: 'Argentina',
        shortName: 'Argentina',
        tla: 'ARG',
        crest: 'https://crests.football-data.org/762.png',
        address: 'Viamonte 1366/76 Buenos Aires, Buenos Aires 1053',
        website: 'http://www.afa.org.ar',
        founded: 1893,
        clubColors: 'Sky Blue / White / Black',
        venue: null,
        lastUpdated: '2022-05-17T21:09:25Z',
      },
    },
    numberOfAvailableSeasons: 22,
    lastUpdated: '2022-05-09T19:45:29Z',
  },
];
